[package]
name = "gleam_finder"
version = "0.2.0"
license = "MIT"
description = "A very small crate you can use to get gleam.io links."
authors = ["Mubelotix <unbeliever.in.time@gmail.com>"]
edition = "2018"

[dependencies]
minreq = { version = "1.4.1", features = ["https"] }